apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager
spec:
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
        - name: cert-manager
          image: gcr.io/arian-241419/cert-manager:latest
          command: ["./cert-manager"]
          ports:
            - containerPort: 5002
      restartPolicy: Never
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cert-manager
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: cert-manager
#   template:
#     metadata:
#       labels:
#         app: cert-manager
#     spec:
#       containers:
#         - name: cert-manager
#           image: gcr.io/arian-241419/cert-manager:latest
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-service
spec:
  ports:
    - port: 80
      targetPort: 5002
  selector:
    app: cert-manager
  type: LoadBalancer
  loadBalancerIP: 104.154.187.165
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: cert-manager-ingress
#   labels:
#     app: cert-manager-ingress
# spec:
#   rules:
#     - http:
#         paths:
#           - backend:
#               serviceName: cert-manager-service
#               servicePort: 80
#             path: /.well-known/acme-challenge
#           - backend:
#               serviceName: cert-manager-service
#               servicePort: 80
